### ISSUE TITLE
Problem setting text on Windows

### ISSUE THREAD

**Issue by danarmstrong** [tucnak/novile#5]
When I attempt to set the text of the editor from the contents of a file on Windows like so:

```
void CodeEditor::loadFile(const QString &path) {

    mFile = new QFile(path);
    if (!mFile->open(QIODevice::ReadOnly)) {
        qWarning() << "Unable to open file: " << path;
        return;
    }

    mEditor->setText(mFile->readAll());
    mEditor->setCursorPosition(0, 0);
    mFile->close();
}
```

the value of mEditor->text() is always ""

This code does work, however, on OS X.

The following does work.
```
mEditor->setText("some text");
```

I also tried this and, again, text comes up empty.
```
QString contents = file.readAll();
mEditor->setText(contents);
```

And since I'm sure you will ask, yes, I have dumped the contents of the file using qDebug and the file is being read correctly.

I'm not sure if I'm doing something wrong but I find it odd (not really) that this is only happening on Windows. Any assistance would be greatly appreciated.

**Comment by tucnak** [comment]
inb4: I'm unfortunately ain't and won't be able to test it on Windows any soon.

Does `setText()` work in other contexts (e.g. called in constructor or called with other contents)? I am currently looking at the [impl](https://github.com/tucnak/novile/blob/master/src/editor.cpp#L219) and it seems supa straight forwards to me, I mean, what could go wrong? Could you please test it with webkit inspector opened as well?

**Comment by danarmstrong** [comment]
I attached an inspector this morning and this is what I get when loading a file:

![image](https://cloud.githubusercontent.com/assets/4072243/12621816/9332f144-c4df-11e5-8761-28967646f0b8.png)

**Comment by danarmstrong** [comment]
I fixed the problem. Will submit a pull request.
